express server added for beanstalk

diff --git a/.github/workflows/deploy-from-web.yml b/.github/workflows/deploy-from-web.yml
--- a/.github/workflows/deploy-from-web.yml
+++ b/.github/workflows/deploy-from-web.yml
@@ -117,11 +117,11 @@ jobs:
           fi
 
           # For beanstalk to work with Vite, a server.js and package.json are copied to the dist directory.
-          if [ -f "$WEBAPP_ROOT/server" ]; then
+          if [ -f "$WEBAPP_ROOT/server/server.js"] && [-f "$WEBAPP_ROOT/server/package.json" ]; then
             cp "$WEBAPP_ROOT/server.js" "$DIST_DIR/"
             cp "$WEBAPP_ROOT/package.json" "$DIST_DIR/"
           else
-            echo "Error: $WEBAPP_ROOT/server not found." 1>&2
+            echo "Error: $WEBAPP_ROOT/server/server.js and it's package.json not found." 1>&2
             exit 1
           fi
 
